### ISSUE TITLE
A question mark appear next to the type in french

### ISSUE THREAD

**Issue by Totoquebec** [CAWSCIT/ca-meeting-finder-issue-tracker#55] opened 2024-08-14 01:44 UTC
**Describe the bug**
When we look at the list of meeting in the french version (it look that affect all localize version except english),  a question mark appear next to the type in french. When we tap on it, a text explain the meaning of the type .
ex. ouvert (open), fermé (closed)
The text that appear make reference to Alcoolic Anonymous instead of Cocaine Anonymous.
The problem did not appear in the english version.

**To Reproduce**
1. Put your phone in french or spanish
2. Go to the Meeting Finder Apps
3. Choose a meeting
4. See the question mark
5. tap on it.

**Expected behavior**
Has in the english version, the question mark should not appear.

**Screenshots**
included

**Additional context**

![french_screen_720](https://github.com/user-attachments/assets/d43437c2-3e9c-49e5-bbb3-83bce045b00b)

**Comment by Totoquebec** [comment] 2024-08-14 01:55
I find where the problem come from.
In the beginning of the file https://meetingfinderstorage.z13.web.core.windows.net/meetings.html the have a "tsml_react_config" to remove the text for the question mark.  Then it look like if the text is remove, then the question mark disapear.
```
<html>
<body>
<!--StartFragment-->
var tsml_react_config = {
          calendar_enabled: false,
          conference_providers: {
              '12steps4hours.org': 'Custom',
              'cocano.org': 'Custom',
              'email.meeting': 'Email',
          },
         /!--  this will supersede the default text for the question mark --/
          strings: {
            en: {
              type_descriptions: {
                O: undefined, 
                C: undefined,
--------> missing bracket closure <------
            },
            fr: {
              type_descriptions: {
                O: undefined,
                C: undefined
              },
            },
<!--EndFragment-->
</body>
</html>

```
In the english section, they have 2 opening brace but just one closing brace. Then I think that the rest of the statement is reject and the other language are not supersede.

**Comment by Totoquebec** [comment] 2024-08-14 02:03
During this process, I realized that this question mark might still be useful to the newbie who doesn't know what "Open" or "Closed" means. It might be possible to put the correct text in this code to describe CA meetings rather than AA meetings.

**Comment by enderv** [comment] 2024-08-14 03:42
Thanks for filing this! We were tracking this under https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/issues/22 but just saw you entered this one...and yep you are correct on the cause! Getting this fixed now

**Comment by enderv** [comment] 2024-08-14 03:51
forgot to say https://github.com/CAWSCIT/ca-meeting-finder-issue-tracker/issues/23 is for tracking  if we want to get in real descriptions in the future

**Closed as completed** 2024-08-14 14:48 UTC
